### ISSUE TITLE
Can't fetch domain by keyword

### ISSUE THREAD

**Issue by augustwu** [threatexpress/domainhunter#10]
I check the code,there is login required when doing domain search,
currently the project can't do domain search
login addr is
https://member.expireddomains.net/login/

**Comment by andrewchiles** [comment]
Thanks for the notice. It looks like there is a change with expireddomains.net. We'll look into it.

**Comment by eviljay** [comment]
the same problem. Looks like expired domains closed an opportunity to check domains without login on site.

**Comment by andrewchiles** [comment]
We could simply require authentication with free account and use the authenticated endpoints or find a new expired domains source. Either way this needs some re-coding

**Comment by eviljay** [comment]
sounds pretty well, i mean adding authentication =)

**Comment by eviljay** [comment]
hey. will you work further with this script? I mean issue about authentication?

**Comment by swarleysez** [comment]
For anyone having issues with auth to ExpiredDomains.net, acole76 submitted a pull request to this branch, which fixes the issue by having you supply your login creds to the command.

Another change is that which searching the top X number of domains, the console output only displays categorizations and not the unwanted results (uncategorized, spam, malicious, etc.).

https://github.com/threatexpress/domainhunter/pull/13

**Comment by andrewchiles** [comment]
Authentication added in latest commit
