### ISSUE TITLE
Expired domains blocking accout

### ISSUE THREAD

**Issue by rewiaca** [threatexpress/domainhunter#16]
Hi!
Thanks for implementing a feature, but as I can see, expireddomains blocking accounts for a several queries from my side via domainhunter.

Maybe it will be good idea to cache all exp domains for one query first and then do search in local disk file?

**Comment by andrewchiles** [comment]
Unfortunately, account blocking will always be a risk with this tool and we recommend being very targeted with your queries to avoid anything that could be considered abuse.

Thanks for the recommendation - a future release could definitely look at grabbing full lists of domains and then performing cache searching offline.
