### ISSUE TITLE
[*] Downloading malware domain list from http://mirror1.malwaredomains.com/files/justdomains

### ISSUE THREAD

**Issue by irena2020** [threatexpress/domainhunter#24]
[*] Downloading malware domain list from http://mirror1.malwaredomains.com/files/justdomains

Password: 

What password? Local? Expireddomains.net? Either way... not working

**Comment by andrewchiles** [comment]
You must specify your ExpiredDomains.net username with the `-u` parameter and password when prompted or via the `-p` parameter
