### ISSUE TITLE
Cannot install Pillow on MacOS Catalina

### ISSUE THREAD

**Issue by captconstruct** [threatexpress/domainhunter#25]
During initial installation of the requirements.txt, I get an error during the install of Pillow. There's LOTS of red text, but at the bottom there's this: "The headers or library files could not be found for zlib, a required dependency when compiling Pillow from source."

**Comment by leebaird** [comment]
Having a similar issue with Kali Linux 2020.2

**Comment by haojianzong** [comment]
use latest pillow by removing version from requirement.txt works for me:

`pillow==5.4.0` -> `pillow`

**Comment by andrewchiles** [comment]
Thanks for the feedback @haojianzong . The version of pillow previously used by the project also had a security issue according to GitHub's dependency bot so I've removed the explicit version from requirements.txt and the latest version should now be used. Hopefully this fixes the issues you all are seeing, but feel free to reopen if it persists after a fresh `git pull`.
