### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'format'

### ISSUE THREAD

**Issue by antonbek89** [threatexpress/domainhunter#30]
When I run the program I got
python3 ./domainhunter.py

[-] Error reaching:{}  Status: {}
Traceback (most recent call last):
  File "./domainhunter.py", line 494, in <module>
    maldomains = downloadMalwareDomains(malwaredomainsURL)
  File "./domainhunter.py", line 263, in downloadMalwareDomains
    print("[-] Error reaching:{}  Status: {}").format(url, response.status_code)
AttributeError: 'NoneType' object has no attribute 'format'

How fix it?

**Comment by xkillbit** [comment]
I get this same error as http://mirror1.malwaredomains.com/files/justdomains does not exist.

**Comment by bridge-four** [comment]
Replacement list for the time being: https://gitlab.com/gerowen/old-malware-domains-ad-list/-/raw/master/malwaredomainslist.txt

**Comment by andrewchiles** [comment]
Thanks all. This is fixed in Master to use the replacement list provided by @bridge-four for now.
