### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by metropot** [threatexpress/domainhunter#39]
Hello,

function:
./domainhunter.py -k apples -c --ocr -t5

i got error mssg:
[-] Error: ExpiredDomains.net requires a username! Use the --username parameter

When i insert login and password in file

Traceback (most recent call last):
  File "./domainhunter.py", line 427, in <module>
    parser.add_argument("-u", "--username", required=False, default=my_login, type=str, help="username for expireddomain.net")
NameError: name 'my_login' is not defined

However "my_login" working fine when i authorize in browser...

**Comment by eucosta** [comment]
I have the exact same problem with the latest version of domainhunter.py
