### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ChrisTruncer** [threatexpress/domainhunter#5]
Hi there, could you let us know what license is used for this project?

**Comment by vestjoe** [comment]
Thanks Chris.  I'll update shortly.  In the meantime, feel free to DM me on twitter if you have a specific question.

**Comment by vestjoe** [comment]
License updated...

**Comment by ChrisTruncer** [comment]
Awesome,

Thanks a lot guys, just wanted to be sure before I started looking at code base.

Thank you!
