### ISSUE TITLE
error using argument -w

### ISSUE THREAD

**Issue by rinkal26783** [threatexpress/domainhunter#8]
C:\DL>domainhunter.py -k pro -w 5

 ____   ___  __  __    _    ___ _   _   _   _ _   _ _   _ _____ _____ ____
|  _ \ / _ \|  \/  |  / \  |_ _| \ | | | | | | | | | \ | |_   _| ____|  _ \
| | | | | | | |\/| | / _ \  | ||  \| | | |_| | | | |  \| | | | |  _| | |_) |
| |_| | |_| | |  | |/ ___ \ | || |\  | |  _  | |_| | |\  | | | | |___|  _ <
|____/ \___/|_|  |_/_/   \_\___|_| \_| |_| |_|\___/|_| \_| |_| |_____|_| \_\

Expired Domains Reputation Checker
Authors: @joevest and @andrewchiles

DISCLAIMER: This is for educational purposes only!
It is designed to promote education and the improvement of computer/cyber security.
The authors or employers are not liable for any illegal act or misuse performed by any user of this tool.
If you plan to use this content for illegal purpose, don't.  Have a nice day :)

[*] Downloading malware domain list from http://mirror1.malwaredomains.com/files/justdomains

[*] Fetching expired or deleted domains containing "pro"
[*]  https://www.expireddomains.net/domain-name-search/?q=pro&fwhois=22&falexa=1
[*]  https://www.expireddomains.net/domain-name-search/?start=25&q=pro&fwhois=22&falexa=1
[*]  https://www.expireddomains.net/domain-name-search/?start=50&q=pro&fwhois=22&falexa=1
[*]  https://www.expireddomains.net/domain-name-search/?start=75&q=pro&fwhois=22&falexa=1

[*] 78 of 78 domains discovered with a potentially desireable categorization!

[*] Search complete
[*] Log written to 20180818_113249_domainreport.html

Traceback (most recent call last):
  File "C:\domainhunter-master\domainhunter.py", line 653, in <module>
    print(drawTable(header,sortedDomains))
  File "C:\domainhunter-master\domainhunter.py", line 283, in drawTable
    return(t.draw())
  File "C:\Users\jaimin26783\AppData\Local\Programs\Python\Python36-32\lib\site-packages\texttable.py", line 372, in draw
    out += self._draw_line(self._header, isheader=True)
  File "C:\Users\jaimin26783\AppData\Local\Programs\Python\Python36-32\lib\site-packages\texttable.py", line 547, in _draw_line
    line = self._splitit(line, isheader)
  File "C:\Users\jaimin26783\AppData\Local\Programs\Python\Python36-32\lib\site-packages\texttable.py", line 586, in _splitit
    array.extend(textwrap.wrap(c, width))
  File "C:\Users\jaimin26783\AppData\Local\Programs\Python\Python36-32\lib\textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "C:\Users\jaimin26783\AppData\Local\Programs\Python\Python36-32\lib\textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "C:\Users\jaimin26783\AppData\Local\Programs\Python\Python36-32\lib\textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -3 (must be > 0)

**Comment by andrewchiles** [comment]
Hello, I wasn't able to reproduce your issue with the current code-base. I also tried with several other queries that returned valid domains without any observed errors. Closing this issue for now. 

```
python3 ./domainhunter.py -k pro -w 5
<title omitted>
Expired Domains Reputation Checker
Authors: @joevest and @andrewchiles

DISCLAIMER: This is for educational purposes only!
It is designed to promote education and the improvement of computer/cyber security.
The authors or employers are not liable for any illegal act or misuse performed by any user of this tool.
If you plan to use this content for illegal purpose, don't.  Have a nice day :)

[*] Downloading malware domain list from http://mirror1.malwaredomains.com/files/justdomains

[*] Fetching expired or deleted domains containing "pro"
[*]  https://www.expireddomains.net/domain-name-search/?q=pro&fwhois=22&falexa=0
[*]  https://www.expireddomains.net/domain-name-search/?start=25&q=pro&fwhois=22&falexa=0
[*]  https://www.expireddomains.net/domain-name-search/?start=50&q=pro&fwhois=22&falexa=0
[*]  https://www.expireddomains.net/domain-name-search/?start=75&q=pro&fwhois=22&falexa=0
[-] No domain results found or none are currently available for purchase!
```
